name: Build and test

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.tex'
    - 'build/**'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.tex'
    - 'build/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run CMake
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Build
      run: |
        cd build
        make -j2
    - name: Test
      run: |
        cd build
        ctest -V
